### ISSUE TITLE
Stable release

### ISSUE THREAD

**Issue by soullivaneuh** [benjamin-smith/php-ipify#2]
Interesting little library. Did you plan a stable release soon? :-)

**Comment by benjamin-smith** [comment]
@Soullivaneuh just realizing I wasn't watching this repo and missed your comment from last year. There is no roadmap here, so I don't see any compelling reason not to bump this to v1.0 stable. Will roll that out soon.

**Comment by benjamin-smith** [comment]
OK all set in dc5f1bcb7ec09cd94533dde54cce5b8f3247ff61
